baseURL: "https://aadimator.com"
languageCode: "en-us"
title: "aadimator"
pygmentsstyle: "monokai"

# Theme settings
theme: novela
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
