baseURL: "https://aadimator.com"
languageCode: "en-us"
title: "aadimator"
pygmentsstyle: "monokai"
sectionPagesMenu: "main"

# Theme settings
theme: novela
paginate: 8
taxonomies:
  author: authors
  tag: tags
  category: categories
  series: series
