---
label: project
hide_body: false
fields:
- type: text
  name: title
  label: title
- name: colorpicker
  type: color
  label: colorPicker
  config:
    required: false
    color_format: Hex
- type: text
  name: color
  label: color
- type: boolean
  name: featured
  label: featured
- type: text
  name: subtitle
  label: subtitle
- type: textarea
  name: description
  label: description
- name: date
  type: datetime
  label: date
  description: ''
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
- type: list
  name: categories
  label: categories
- type: list
  name: tags
  label: tags
- type: list
  name: authors
  label: authors
- type: field_group_list
  name: resources
  label: resources
  fields:
  - type: text
    name: src
    label: src
  - type: text
    name: name
    label: name
